import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import { api } from "@/utils/api";
import { Hero } from "@/components/Hero/Hero";

function QuizCard() {
  return <div className="h-20 w-full rounded bg-dark-300 md:max-w-[320px]" />;
}

export default function Home() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />

      <p className="mb-3 pt-5 text-center text-xl font-bold text-white">
        Najnowsze Quizy
      </p>
      <p className="mb-5 text-center text-white">
        Oto Quizy, które utworzyli nasi użytkownicy. Przeglądaj śmiało!
      </p>

      <div className="mx-5 grid grid-cols-2 gap-2.5 md:mx-8 md:grid-cols-3 lg:mx-auto lg:max-w-screen-lg lg:grid-cols-4">
        <QuizCard />
        <QuizCard />
        <QuizCard />
        <QuizCard />
      </div>
    </>
  );
}
